import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import fs from "fs";
import { sassPlugin } from "esbuild-sass-plugin";
import { copy } from "esbuild-plugin-copy";
import svg from "esbuild-plugin-svg";

const prod = process.argv[2] === "production";

const renameCssPlugin = () => ({
  name: "rename-css-plugin",
  setup(build) {
    build.onEnd(() => {
      if (fs.existsSync("./main.css")) {
        fs.renameSync("./main.css", "./styles.css");
      }
    });
  }
});

const buildOptions = {
  banner: {
    js: `/*\nGenerated by esbuild for local Obsidian AnyNote development.\n*/\n`
  },
  entryPoints: ["./src/main.ts"],
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtins
  ],
  format: "cjs",
  target: "es2020",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  outfile: "./main.js",
  plugins: [
    sassPlugin({
      filter: /.(s[ac]ss|css)$/
    }),
    svg(),
    copy({
      resolveFrom: "cwd",
      assets: {
        from: ["./src/static/**/*"],
        to: ["./"]
      },
      watch: false
    }),
    renameCssPlugin()
  ],
  define: {
    "process.env.NODE_ENV": JSON.stringify(prod ? "production" : "development")
  }
};

if (prod) {
  await esbuild.build(buildOptions).catch(() => process.exit(1));
} else {
  const context = await esbuild.context(buildOptions);
  await context.watch();
  console.log("Watching for changes...");
}
